# Generated by Django 3.2.4 on 2021-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
