# Generated by Django 3.2.4 on 2021-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
